
project_id = "fubgdbbvspdkxdfetvxm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[api.linkTokens]
dev = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 604800
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true
template_create_user = """
<h2>Confirm your signup</h2>
<p>Follow this link to confirm your user:</p>
<p><a href="{{ .SiteURL }}/auth/confirm?token={{ .TokenHash }}&type=signup&redirect_to={{ .RedirectTo }}">Confirm your email</a></p>
"""
template_magic_link = """<h2>Magic Link</h2>
<p>Follow this link to login:</p>
<p><a href="{{ .SiteURL }}/auth/confirm?token={{ .TokenHash }}&type=invite&redirect_to={{ .RedirectTo }}">Log In</a></p>
"""

[functions]
enabled = true
path = "supabase/functions"

[functions.plaid-create-link-token]
verify_jwt = true

[functions.plaid-exchange-token]
verify_jwt = true

[functions.plaid-get-accounts]
verify_jwt = true

[local.postgres.auth]
secret_key = "super-secret-jwt-token-with-at-least-32-characters-long"
