
-- Add video_url column to education_lessons
ALTER TABLE education_lessons 
ADD COLUMN IF NOT EXISTS video_url TEXT;

-- Create a table for quizzes
CREATE TABLE IF NOT EXISTS education_quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  options JSONB NOT NULL,
  correct_option INTEGER NOT NULL,
  explanation TEXT,
  lesson_id BIGINT REFERENCES education_lessons(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create a table to track user lesson progress
CREATE TABLE IF NOT EXISTS user_lesson_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  lesson_id BIGINT REFERENCES education_lessons(id) ON DELETE CASCADE,
  completed BOOLEAN DEFAULT FALSE,
  score INTEGER,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, lesson_id)
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS education_quizzes_lesson_id_idx ON education_quizzes(lesson_id);
CREATE INDEX IF NOT EXISTS user_lesson_progress_user_id_idx ON user_lesson_progress(user_id);
CREATE INDEX IF NOT EXISTS user_lesson_progress_lesson_id_idx ON user_lesson_progress(lesson_id);
