// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fubgdbbvspdkxdfetvxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1YmdkYmJ2c3Bka3hkZmV0dnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzE4MjEsImV4cCI6MjA2MDI0NzgyMX0.oQgcQ6dJIk60OPI76QRNla6f4qXgbevIXiGx-Nfogn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);